/* Example table containing all MySQL data types for template checking. */
CREATE TABLE `all_mysql_types` (
  `my_bit` bit(1) DEFAULT NULL,
  `my_tinyint` tinyint(4) DEFAULT NULL,
  `my_boolean` tinyint(1) DEFAULT NULL,
  `my_smallint` smallint(6) DEFAULT NULL,
  `my_mediumint` mediumint(9) DEFAULT NULL,
  `my_int` int(11) DEFAULT NULL,
  `my_bigint` bigint(20) DEFAULT NULL,
  `my_decimal_10_5` decimal(10,5) DEFAULT NULL,
  `my_float` float DEFAULT NULL,
  `my_double` double DEFAULT NULL,
  `my_date` date DEFAULT NULL,
  `my_datetime` datetime DEFAULT NULL,
  `my_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `my_time` time DEFAULT NULL,
  `my_year` year(4) DEFAULT NULL,
  `my_char_10` char(10) DEFAULT NULL,
  `my_varchar_10` varchar(10) DEFAULT NULL,
  `my_binary` binary(100) DEFAULT NULL,
  `my_varbinary` varbinary(100) DEFAULT NULL,
  `my_tinyblob` tinyblob,
  `my_tinytext` tinytext,
  `my_blob` blob,
  `my_text` text,
  `my_mediumblob` mediumblob,
  `my_mediumtext` mediumtext,
  `my_longblob` longblob,
  `my_longtext` longtext,
  `my_enum_abc` enum('a','b','c') DEFAULT NULL,
  `my_set_def` set('d','e','f') DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
