# Changes zero date values generated by MySQL to nulls.  MySQL permits the 
# value 0 but other DBMS implementations like Oracle do not. 
replicator.filter.zerodate2null=com.continuent.tungsten.replicator.filter.JavaScriptFilter                                
replicator.filter.zerodate2null.script=${replicator.home.dir}/support/filters-javascript/zerodate2null.js
